on: [push]
name: linelint

jobs:
  linelint:
    runs-on: ubuntu-latest
    name: Check if all files end in newline
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: files
        uses: jitterbit/get-changed-files@v1
      - run: |
          echo "${{ steps.files.outputs.all }}"
      
      - name: Linelint
        uses: fernandrone/linelint@0.0.4
        id: linelint
        with: 
          args:  ${{ steps.files.outputs.all }}
          entryPoint: .